### ISSUE TITLE
Loading locale data at runtime

### ISSUE THREAD

**Issue by dyniper** [i18next/i18next-icu#1]
Hello, I was wondering how you suggest this is used when loading locale remotely at runtime. For example, if this is used with i18next XHR module, changing ones locale would require to do
`icu.addLocaleData({newLocaleData});` somewhere.

Ideally I would not want to bundle all the locale data in my application bundle, thus I am looking at some guidance on how to achieve that.

Thanks!

**Comment by jamuhl** [comment]
There are two options...you load that additional script before you call `i18next.changeLanguage` or you call and add it on the event: https://www.i18next.com/overview/api#onlanguagechanged

**Comment by dyniper** [comment]
Thanks for the answer @jamuhl . Just to make sure i understand, you would do a xhr call manuallyt on the file (which would be hosted with your application), and on the success of that call add it to the icu instance? Then the it would automatically be reflected in the i18next instance?

**Comment by jamuhl** [comment]
Yes...it basically passes that to the IntlMessageFormat: https://github.com/i18next/i18next-icu/blob/master/src/index.js#L30

And on calling `t` it uses: https://github.com/i18next/i18next-icu/blob/master/src/index.js#L47 the language from i18next (also memoize works with different languages)

**Comment by dyniper** [comment]
Perfect. I'll reopen this if i need more help while using the above. Thanks!

**Comment by jamuhl** [comment]
do not load the js file via xhr -> add a script element to the html to load it. Guess for inspiration you can use: https://www.npmjs.com/package/react-async-load-script

**Comment by dyniper** [comment]
Ok, but then how do i register them with my icu instance? Do those files exports some global that i can use in icu.addLocaleData?

**Comment by jamuhl** [comment]
those are taken from reactIntl -> are on global.ReactIntlLocaleData[lng] i guess from looking the code

**Comment by dyniper** [comment]
Hmmm, that doesn't seem to work. See this fiddle: https://jsfiddle.net/j3o40765/

**Comment by dyniper** [comment]
Nevermind, it works, fixed the fiddle. I think i'm good to go. Thanks for your help again.

**Comment by jamuhl** [comment]
Awesome...glad you figured out.

**Comment by jamuhl** [comment]
Just found another option if you're using webpack https://github.com/locize/locize-react-intl-example/blob/master/src/locize/index.js#L39 (just change path accordingly)

**Comment by jamuhl** [comment]
updated link to sample: https://github.com/locize/locize-react-intl-example/blob/master/src/locize/index.js#L53
