### ISSUE TITLE
Does the locale data files really have to be so big?

### ISSUE THREAD

**Issue by baldurh** [i18next/i18next-icu#10]
es.js is 13.4KB, en.js is 7.2KB but jp.js is only 1.13KB
Why is there’s so much difference? Do these files really have to have so many actual translations? Couldn’t they just include the ICU rules and not the actual words?

**Comment by jamuhl** [comment]
🤷‍♂️ was taken from https://github.com/formatjs/intl-messageformat on time of creation...not sure that got improved meanwhile...

**Comment by baldurh** [comment]
We only needed the plural rules so I ended up creating an extraction script for our purposes. Anyone interested can find it here: https://gist.github.com/baldurh/f2155e522eae90aab7872d33d24608e8
