### ISSUE TITLE
skipInterpolation option is not being respected

### ISSUE THREAD

**Issue by axelfriberg** [i18next/i18next-icu#11]
When using this plugin and trying to do `t('stringId', { skipInterpolation: true }` you simply get and error message "The intl string context variable 'abc' was not provided to the string...".

**Comment by jamuhl** [comment]
As soon i18next is handling a format like fluent, ICU it fully passed the control over to the underlaying 3rd party i18n implementation -> so that option only exists for i18next's own format: https://github.com/i18next/i18next/blob/master/src/Translator.js#L269

**Comment by axelfriberg** [comment]
Ah okey I see. Do you have any suggestions how you would go about trying to get the same behaviour as "skipInterpolation" but using this plugin?

**Comment by jamuhl** [comment]
You can get the raw value by accessing i18next.getResource https://www.i18next.com/overview/api#getresource but guess that is not what you need (you just like to skip interpolation but keep eg. plural handling)

**Comment by axelfriberg** [comment]
For this particular use case I actually think getResource might work! Thanks, for the tip.
