### ISSUE TITLE
Memoized cache should be busted when new resources are added

### ISSUE THREAD

**Issue by offirgolan** [i18next/i18next-icu#17]
I ran into this issue when setting up react-i18next with gatsby when hot reloading the translations weren't working. This was a major troll not gonna lie lol.

```js
i18next.addResourceBundle(locale, 'translation', { foo: 'bar' }, false, true);
i18next.t('foo') // => 'bar'
i18next.addResourceBundle(locale, 'translation', { foo: 'baz' }, false, true);
i18next.t('foo') // => 'bar'
```

```json
"dependencies": {
    "i18next": "^19.3.2",
    "i18next-icu": "^1.2.1",
    "react-i18next": "^11.3.3"
  },
```

My current work around is to turn off `memoize` in the dev environment but I feel like this should be something handled by this library or provide a way to manually clear the cache.

**Comment by jamuhl** [comment]
setting `i18next.services.i18nFormat.mem = {}` should do the trick. Not sure how we should handle this...we do not really know if this runs in development or production.

**Comment by offirgolan** [comment]
Wouldn't you want to bust the cache regardless of the environment if any resources are changed? Can you do something like

```js
i18next.store.on('added removed', () => {
  i18next.services.i18nFormat.mem = {}
});
```

Doing this in my codebase seems very fragile since `mem` is a private field. If anything, could you provide a public and documented API to clear the cache? 

`i18next.services.i18nFormat.clearCache()`

**Comment by jamuhl** [comment]
Feel free to add a PR which adds either a clearCache function or options to set bindings for store and i18next event (defaulting to none) which clears the cache on events defined passed as options like we eg. do in react-i18next: https://github.com/i18next/react-i18next/blob/master/src/context.js#L4
