### ISSUE TITLE
Unable to add custom format.

### ISSUE THREAD

**Issue by AndriiTsarenko** [i18next/i18next-icu#19]
I'm looking for the possibility to add default values to interpolation.  
For example, I have this key: `'Hello {user}'`
And `user` in my case is optional.
So what I want to add `defaultValue` formatter. 
And my key should look like `'Hello {user, devaultValue, a user}'` 
And I didn't find out a way to add such formatter.

**Comment by jamuhl** [comment]
I'm not too deep into messageformat -> is there something like a custom formatter

**Comment by jamuhl** [comment]
What I want to say with this...if it's not supported in formatjs - it's not supported here

**Comment by AndriiTsarenko** [comment]
Ok I see.
