### ISSUE TITLE
Using i18next formatter with i18next-icu

### ISSUE THREAD

**Issue by dyniper** [i18next/i18next-icu#2]
Hello, is using i18next formatting ( https://www.i18next.com/translation-function/formatting ) with i18next-icu possible? If yes, what is the syntax to use?

Thanks!

**Comment by jamuhl** [comment]
No...icu is a own i18n format which comes with it's own formatting rules: https://formatjs.io/guides/message-syntax/

**Comment by dyniper** [comment]
Do you think it is something that could be feasible to implement? For example, something like this:
"{myVariable, custom, args}", where basically if reading "custom" as the format, it would defer to i18next formatting function? Or is it too late already at that point? I guess I'm lacking the understanding on how i18next-icu actually bridge to i18next (if at all).

Thanks for such a quick response!

**Comment by dyniper** [comment]
Ah, i see, it simply defer the work to IntlMessageFormat. I guess that would be pretty hard to hook it to i18next formatter. Oh well, thanks for the help again!

**Comment by jamuhl** [comment]
Would be possible i guess....but really mixing them would make it look like a new format which just adds more complexity (eg. think of translation management tools like our https://locize.com - that would suddenly have to support i18next, icu and i18next+icu mix format - which would be harder than adding it here - so better keep formats clean)
