### ISSUE TITLE
How to handle different timezones in nodejs

### ISSUE THREAD

**Issue by shadizar128** [i18next/i18next-icu#20]
Hi, I am trying to use this module in nodejs to send emails to different customers. Each customer can have a different language and/or timezone. Do you have any examples on how to set the timezone per call? All i have now is this

```
function getText(lang) {
  return i18next.t('This is an example of date formatting: {value, date, short}', {lang: lang, value: new Date()});
}
```

**Comment by jamuhl** [comment]
you might have a look at: https://momentjs.com/timezone/

**Comment by jamuhl** [comment]
And further you might look at formatjs website - as i18next-icu used that

**Comment by shadizar128** [comment]
Using momentjs or formatjs would imply I not use this module at all, right?

**Comment by jamuhl** [comment]
using momentjs yes

formatjs -> this module is based on the formatjs implementation

**Comment by shadizar128** [comment]
And formatjs uses Intl.DateTimeFormat as I see it but its options are not exposed in i18next-icu. (I can only set:
```
i18next
  .use(ICU)
  .init({
    i18nFormat: {
      formats: {}
    }
  });
```
However, this is a static config, I cannot change it on a call by call basis.

**Comment by jamuhl** [comment]
Like said...it replaces the format used by i18next with the one from formatjs -> there is no mix
