### ISSUE TITLE
Define an actual interface for IntLocaleData

### ISSUE THREAD

**Issue by ranst91-u** [i18next/i18next-icu#22]
The IntLocaleData TS interface looks like this:
`interface IntlLocaleData {}`

My suggestion is to define an actual interface for this.
Otherwise, when trying to grab a property of a specific locale object, every property I'll try to get, will hit a `Property '...' does not exist on type 'LocaleData'`

Otherwise, there is no way to work with the default export of the locale data with TS

**Comment by jamuhl** [comment]
Feel free to provide a PR
