### ISSUE TITLE
Currency Message Format not working.

### ISSUE THREAD

**Issue by ojassvi** [i18next/i18next-icu#28]
## 🐛 Bug Report

I am using react-i18next with i18next-icu to support Intl Message formatting. It works as defined here https://formatjs.io/docs/intl-messageformat for Date, Time, Number and Plurals but does not work for currency. I tested this with `Intl-messageformat` alone and the currency formatting works fine, but doesn't work with i18next-icu. 

`i18next-icu` uses `intl-message` version 2.2.0 but the latest version available is 9.3.20. The issue is still there with the latest version as well.

## To Reproduce
Here is the [codesandbox](https://codesandbox.io/s/zealous-sky-6e97q?file=/src/App.js) link to reproduce the issue. The error case is shown is red and the expected behaviour in green.

## Expected behavior

I expect the string `{price, number, ::currency/CAD}"` to be formatted through Intl Message format as currency but it is formatting this as a number.

## Your Environment

- *runtime version*: i.e. node v12.19.0
- *i18next version*: i.e. 19.8.4
- *os*: Mac

**Comment by jamuhl** [comment]
Not sure why it does not work: https://github.com/i18next/i18next-icu/blob/master/src/index.js#L81

Might be the https://github.com/i18next/i18next-icu/tree/master/locale-data should be updated to add the currency formatting?!?

PR welcome

**Comment by ojassvi** [comment]
Thanks for the update. I will dig into it and will send a PR in a few days.

**Comment by jamuhl** [comment]
this module was updated v2.0.0

**Comment by ojassvi** [comment]
Thanks, it did fix the issue.
