### ISSUE TITLE
ICU will ignore the first blank in plural

### ISSUE THREAD

**Issue by acdzh** [i18next/i18next-icu#29]
## 🐛 Bug Report

Hello! I found the icu will ignore the first blank in plural, just like this demo. Please look at the `{ a}` in ` key1`. **Is this a bug or just a feature?** Is there any way to solve this problem? Because our i18n translations are auto-generated like `key1`, It is diffcullt to change the translation to like `key2`. Thanks!

![image](https://user-images.githubusercontent.com/32260125/103508832-bc8aa680-4e9c-11eb-882e-be38c47f8a51.png)

## To Reproduce

[codepen](https://codepen.io/acdzh/pen/OJRvrzO)

or

```html
<div>
  <div>key1: {count} apple{num, plural, one { a} other{s two}} day, keep doctor away.</div><br />
  <div>1 apple: <div id="div11"></div></div><br />
  <div>2 apple: <div id="div12"></div></div><br />
</div>
<br />
<div>
  <div>key2: {count} {num, plural, one {apple a} other{apples two}} day, keep doctor away.</div><br />
  <div>1 apple: <div id="div21"></div></div><br />
  <div>2 apple: <div id="div22"></div></div><br />
</div>
```

```js
const translation = {
  key1: '{count} apple{num, plural, one { a} other{s two}} day, keep doctor away.',
  key2: '{count} {num, plural, one {apple a} other{apples two}} day, keep doctor away.'
};

i18next.use(ICU).init({
  lng: "en",
  resources: {
    en: { translation }
  }
});


const div11 = document.getElementById('div11');
const div12 = document.getElementById('div12');
const div21 = document.getElementById('div21');
const div22 = document.getElementById('div22');

div11.innerText = i18next.t('key1', {count: 1, num: 1});
div12.innerText = i18next.t('key1', {count: 2, num: 2});
div21.innerText = i18next.t('key2', {count: 1, num: 1});
div22.innerText = i18next.t('key2', {count: 2, num: 2});
```

## Expected behavior

We want the key1 and key2 have the same result.

## Your Environment

- *runtime version*: node v14.15.0, Crome 87
- *i18next version*: 19.8.4
- *i18next-icu version*: 1.4.2
- *os*: Mac and Linux

**Comment by jamuhl** [comment]
the ICU variant of i18next depends on the implementation used in react-intl: https://github.com/i18next/i18next-icu/blob/master/package.json#L18

so, if an issue it would need to be solved there...

but honestly I recommend you to not build up your strings like you do as messageformat encourages having full sentences

```
{
   count, plural,
     one {One apple a day, keep the doctor away}
   other {# apples a day, keep the doctor away }
 }
```

**Comment by acdzh** [comment]
> the ICU variant of i18next depends on the implementation used in react-intl: https://github.com/i18next/i18next-icu/blob/master/package.json#L18
> 
> so, if an issue it would need to be solved there...
> 
> but honestly I recommend you to not build up your strings like you do as messageformat encourages having full sentences
> 
> ```
> {
>    count, plural,
>      one {One apple a day, keep the doctor away}
>    other {# apples a day, keep the doctor away }
>  }
> ```
tks
