### ISSUE TITLE
memoize saves fallback with async backend

### ISSUE THREAD

**Issue by beheh** [i18next/i18next-icu#3]
In our app, we use key-based fallback with an asynchronous i18next backend with react-i18next and i18next-icu.

When using react-icu with the default settings, it looks like memoization incorrectly memoizes the fallback keys, even after the translations have been loaded.

I can fix this right now by calling `ICU.mem = {}` manually after a new translation has been loaded. This should probably not happen in the first place though.

Alternatively, you might want to expose a (documented) method to clear the memoization cache.

**Comment by jamuhl** [comment]
Will look into this tomorrow....guess best would to be just not memoize in case of fallbacking to key? Agree?

**Comment by beheh** [comment]
Yeah, we had it disabled so far due to this issue. We're looking into some performance regressions on our site right now, so I was playing around with reenabling it which led me to the workaround of manually clearing the memoization cache.

**Comment by jamuhl** [comment]
should work with:

i18next@11.3.3
i18next-icu@0.4.0

https://github.com/i18next/i18next/commit/dd9cabcebc8a5919abad2c40c7be0bc65a94afca#diff-42176d501e1082b1431ec21640f0ff05

->

https://github.com/i18next/i18next-icu/commit/133d2976d8ab22bcd6c3afd8da914f32f7e32084#diff-1fdf421c05c1140f6d71444ea2b27638R51

**Comment by beheh** [comment]
Thanks for a quick release, this looks fixed! :+1:

**Comment by jamuhl** [comment]
awesome...if you encounter any other issue let me know....i18next-icu still rather fresh
