### ISSUE TITLE
Upgrading to 2.0.2 - Failed to Compile - Module not found

### ISSUE THREAD

**Issue by citylife4** [i18next/i18next-icu#36]
Hello,

I was following this tutorial that help me set up i18next-icu on my react app.
https://medium.com/@danduan/translating-react-apps-using-i18next-d2f78bc87314

It was working fine, but when updating from 1.4.2 to 2.0.2 the following error started appearing:

```
./src/i18nextConf.js
Module not found: Can't resolve 'i18next-icu/locale-data/en' in '/home/valverde/dev/sabores-ecommerce/frontend/src'
```

Is there something that needs to be changed on the apps to upgrade to 2.0.2?

Thanks for the help

**Comment by jamuhl** [comment]
i guess loading locale-data is no longer needed as all major browsers provide the Intl API

**Comment by citylife4** [comment]
Indeed removing locale-data does not impact the app itself.
Thanks for the help
