### ISSUE TITLE
addLocaleData functionality is removed in 2.0 and no migration docs are provided

### ISSUE THREAD

**Issue by givethemheller** [i18next/i18next-icu#43]
Previous version 1.4.X included instructions on how to add a language at runtime. 

```
import i18next from 'i18next';
import ICU from 'i18next-icu';
import fr from 'i18next-icu/locale-data/fr';

const icu = new ICU();
icu.addLocaleData(fr);
```

This methodology is completely removed from the 2 release and I cannot find any instructions or migration documentation. 

Can someone please provide some guidance on why this was removed, what its impact is and how to mitigate it on upgrade? Links to other documentation would be fantastic. Happy to make a PR to update docs here to help other folks out.

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-icu/issues/42 not needed anylonger

**Comment by givethemheller** [comment]
@jamuhl I get that this is expected and by intent in the major, but for the sake of every engineer being tasked with dependency updates, it would be really helpful to have some documentation in the repo. A note that says "this is no longer needed" and a link to the react example seems reasonable?

**Comment by jamuhl** [comment]
https://github.com/i18next/i18next-icu/blob/master/README.md#migration-guide
