### ISSUE TITLE
In-built currency formatting not working with ICU

### ISSUE THREAD

**Issue by Wildhoney** [i18next/i18next-icu#50]
Codesandbox: https://codesandbox.io/s/competent-wildflower-kpvrl5?file=/src/index.ts

When using ICU the [built-in currency formatting](https://www.i18next.com/translation-function/formatting#currency) doesn't seem to work at all &mdash; if you uncomment lines 2 and 4 you'll see that it breaks.

**Comment by adrai** [comment]
The built-in formatting is only for the i18next i18n format... but since you're using i18next-icu, this is a different i18n format and you need to check ICU instead...
i.e. `"The price is: {price, number, ::currency/GBP}"`

https://codesandbox.io/s/pedantic-poincare-jgnwzz

**Comment by Wildhoney** [comment]
I did check with `i18next-icu` and that ☝️ does work fine. I couldn't find a way in the docs to automatically add the currency symbol though for a custom formatter &mdash; in the in-built docs it seems to be a lot easier.

I'm currently using the following custom formatter for price:

```javascript
icu.addUserDefinedFormats({
    number: {
        PRICE_FORMAT: {
            minimumFractionDigits: 0,
            maximumFractionDigits: 2,
        },
    },
});
```

Is there a way to also add `::currency/GBP`?

**Comment by jamuhl** [comment]
formats depend on `IntlMessageFormat` https://github.com/i18next/i18next-icu/blob/master/src/index.js#L66

as this basically just wraps that implementation of ICU messageformat - so you will have to look there what is possible or not
