### ISSUE TITLE
Enabling ICU breaks interpolation

### ISSUE THREAD

**Issue by the-line** [i18next/i18next-icu#56]
## 🐛 Bug Report

When ICU is enabled on i18next with react-i18next, some interpolations aren't executed. When .use(ICU) is commented out, the interpolation is working correctly.

## To Reproduce

https://codesandbox.io/s/icu-interpolation-bug-ix0cl3

## Expected behavior

The text "User test has been created" is shown on the page.

## Actual behavior

The text "User {{ what }} has been created" is shown on the page. Notice that the interpolation is not executed.

## Your Environment

- *runtime version*: Google Chrome 107.0.5304.107 and Mozilla Firefox 107.0
- *i18next version*: i.e. 22.0.6
- *i18next-icu version*: 2.0.3
- *react-i18next version*: 12.0.0
- *react version*: 18.2.0
- *intl-messageformat version*: 9.13.0
- *os*: Windows 11 22H2 (22621.819)

**Comment by adrai** [comment]
You used the wrong interpolation parenthesis...
for ICU it is: `User { what } has been created` instead of `User {{ what }} has been created`

**Comment by the-line** [comment]
That was the problem! Thank you very much for your time to figure this out :)

Maybe mentioning in the documentation when using ICU that the i18next interpolation rules should be used and only ICU interpolation rules will work.

**Comment by adrai** [comment]
> That was the problem! Thank you very much for your time to figure this out :)
> 
> Maybe mentioning in the documentation when using ICU that the i18next interpolation rules should not be used and only ICU interpolation rules will work.

https://github.com/i18next/i18next-icu#advice

**Comment by the-line** [comment]
Thanks again, and this was a nice case of "You should read the manual".

Sorry about that.

**Comment by the-line** [comment]
I have changed the sandbox code to point this difference out for reference if someone find this issue.
