### ISSUE TITLE
Plural and number format combination

### ISSUE THREAD

**Issue by felicoz** [i18next/i18next-icu#65]
Hi, I have search through the google and github and no luck with a solution so I start an thread to ask.

Shop {numOfItems, plural, =1 {1 Item} other {# Items}}

My goal is to have number and plural formation together from a key:
English: Shop 10,000 Items
French: Shop 10 000 Items

But I am getting the following at the moment:
English: Shop 10,000 Items
French: Shop 10,000 Items

Is that possible? currently seems like I can only do either number or plural or currency separately.

```
"i18next": "^20.3.5",
"i18next-browser-languagedetector": "^6.1.3",
"i18next-chained-backend": "^4.2.0",
"i18next-http-backend": "^2.2.1",
"i18next-icu": "^2.0.3",
"i18next-localstorage-backend": "^4.1.1",
"next-i18next": "^12.1.0",
```

If I try to localize the number myself, the final result becomes a string "10,000" and won't be able use the ICU plural format.

thanks!

**Comment by adrai** [comment]
Seems to work as expected: https://codesandbox.io/s/friendly-joana-s7mdv7?file=/src/index.mjs
<img width="1229" alt="image" src="https://github.com/i18next/i18next-icu/assets/1086194/2a0e5594-a3e7-45c1-824b-2fe5c55d6134">

https://format-message.github.io/icu-message-format-for-translators/editor.html
<img width="1223" alt="image" src="https://github.com/i18next/i18next-icu/assets/1086194/01b647f8-9a45-48ef-8940-60b9c546b044">

**Comment by felicoz** [comment]
oops my bad, it does work...
