### ISSUE TITLE
Fallback strings are not formatted using the target locale.

### ISSUE THREAD

**Issue by SpikyC** [i18next/i18next-icu#67]
## 🐛 Bug Report

Any translations that uses fallback strings will also use the fallback locale to format them instead of the target locale.
Using `{{date, datetime}}` without _i18next-icu_ the fallback would still use the target locale to format the date.

### Fallback to en
```js
import i18next from "i18next";
import ICU from "i18next-icu";

i18next.use(ICU).init({
  lng: "fr-CA",
  resources: {
    en: {
      translations: {
        short_date: "{date, date, short}"
      }
    }
  }
});

i18next.t("short_date", { date: new Date(2000, 1, 29) }); // 2/29/00 (Which is the en-US way to write it.)
```
### Fallback to fr
```js
import i18next from "i18next";
import ICU from "i18next-icu";

i18next.use(ICU).init({
  lng: "fr-CA",
  resources: {
    en: {
      translations: {
        short_date: "{date, date, short}"
      }
    },
    fr: {
      translations: {
        short_date: "{date, date, short}"
      }
    }
  }
});

i18next.t("short_date", { date: new Date(2000, 1, 29) }); // 29/02/00 (Which is the fr-FR way to write it.)
```

## Expected behavior
```js
import i18next from "i18next";
import ICU from "i18next-icu";

i18next.use(ICU).init({
  lng: "fr-CA",
  resources: {
    en: {
      translations: {
        short_date: "{date, date, short}"
      }
    }
  }
});

i18next.t("short_date", { date: new Date(2000, 1, 29) }); // 00-02-29 (Which is the fr-CA way to write it.)
```

## Your Environment

- *runtime version*: node v18.17.0, npm 9.6.7, deno, browser Chrome/116.0.0.0
- *i18next version*: 23.4.5
- *os*: Windows 10 (WSL Ubuntu 20.04)

**Comment by adrai** [comment]
The language code in the resources is important.

So, this works:


```js
i18next.use(ICU).init({
  debug: true,
  lng: "fr",
  fallbackLng: "fr-CA",
  resources: {
    "fr-CA": {
      translation: {
        short_date: "fr-CA: {date, date, short}"
      }
    },
    "en-CA": {
      translation: {
        short_date: "en-CA: {date, date, short}"
      }
    }
  }
});

i18next.t("short_date", { date: new Date(2000, 1, 29) }) // fr-CA: 00-02-29
i18next.t("short_date", { date: new Date(2000, 1, 29), lng: 'en-CA' }) // en-CA: 00-02-29
```

**Comment by SpikyC** [comment]
Hello @adrai,
While I know that providing the string in the resources will mitigate the issue, I’m saying that the normal behaviour of _i18next_ is to format the string with the target locale as a base.
```javascript
import i18next from 'i18next';

i18next.init({
  lng: "fr-CA",
  resources: {
    en: {
      translations: {
        date: "{{date, datetime}}"
      },
    },
  },
});

console.log(i18next.t("date", { date: new Date(2000, 1, 29) })); // 2000-02-29 (Which is the fr-CA value using Intl.DateTimeFormat.)
``` 

```javascript
import i18next from 'i18next';

i18next.init({
  lng: "fr",
  resources: {
    en: {
      translations: {
        date: "{{date, datetime}}"
      },
    },
  },
});

console.log(i18next.t("date", { date: new Date(2000, 1, 29) })); // 29/02/2000 (Which is the fr-FR value using Intl.DateTimeFormat.)
```

**Comment by adrai** [comment]
Can you try with i18next v23.4.6 ?

**Comment by jamuhl** [comment]
wrong...format inside gets done with the language i18next is able to resolve a resource -> if it resolves the `en` string it will format dates in english format and not in french -> to keep a string consistent

**Comment by SpikyC** [comment]
> Can you try with i18next v23.4.6 ?

It solved the issue, thanks!

**Comment by jamuhl** [comment]
23.4.6 is breaking change and wrong -> rollback is needed

**Comment by SpikyC** [comment]
> 23.4.6 is breaking change and wrong -> rollback is needed

While I agree that it is a breaking change, I don’t understand why it is wrong since it’s the default behavior of _i18next_?

**Comment by jamuhl** [comment]
then the default behaviour might be wrong - formatting and language should be consistent...or do you like german strings with american dates?

**Comment by SpikyC** [comment]
> then the default behaviour might be wrong - formatting and language should be consistent...or do you like german strings with american dates?

Then it’s no use to follow this principle since those format might not be valid.
https://www.i18next.com/principles/fallback#variant-resolving-fallback-from-dialects-or-scripts

**Comment by jamuhl** [comment]
in that case we would have to decide on locale for formatting depending if it is a fallback to non regional variant...so you're right...both options are currently wrong depending on the fallback comes from same language or not

**Comment by SpikyC** [comment]
> in that case we would have to decide on locale for formatting depending if it is a fallback to non regional variant...so you're right...both options are currently wrong depending on the fallback comes from same language or not

As a compromise, I would be happy with that solution.

**Comment by jamuhl** [comment]
so as change already made we keep current change in hope we did not open a box ;)

**Comment by adrai** [comment]
ok, let's close this issue now ;-)
